[package]
name = "zippy-core"
version.workspace = true
edition.workspace = true
readme.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
